Upgrade Mattermost to v8.1 ESR
osuosl-cookbooks/osl-mattermost pull request #3
Opened 2023-12-08 20:46 UTC by ArtofBugs

2023-12-08 20:47 UTC, ArtofBugs commented
> In v8.0, the following repositories are merged into one: mattermost-server, mattermost-webapp and mmctl. Developers should read the updated [Developer Guide](https://developers.mattermost.com/contribute/developer-setup/) for details.

Looks like a separate mmctl isn't supported anymore... for future reference, the migration guide is here https://developers.mattermost.com/contribute/monorepo-migration-notes/

2023-12-11 18:29 UTC, ramereth requested changes

2023-12-11 18:29 UTC, ramereth commented on resources/mattermost.rb
> -
So this actually got moved to the single tarball. If you download https://releases.mattermost.com/8.1.7/mattermost-8.1.7-linux-amd64.tar.gz and then extract the file at `mattermost/bin/mmctl` that will get you what you need. I believe the `ark` resource allows you to grab a specific binary. Can you please bring this back? We'll just set the mmctl version to the mattermost semver version.

2023-12-14 17:47 UTC, ramereth commented on resources/mattermost.rb
> +    url "https://releases.mattermost.com/#{new_resource.mmctl_version}/mattermost-#{new_resource.mmctl_version}-linux-amd64.tar.gz"
Can you please move this to the top like it was before?

2023-12-14 18:11 UTC, ramereth commented
@ArtofBugs you need to update the link resource to point to the new location for mmctl

2023-12-15 01:21 UTC, ArtofBugs commented
> @ArtofBugs you need to update the link resource to point to the new location for mmctl

Yep, finally figured out how the `ark` installation path thing works... 😅

2023-12-19 19:19 UTC, ramereth approved these changes
I will coordinate with customer and merge/deploy this

2023-12-19 19:46 UTC, ramereth commented
!bump minor ~

2023-12-19 19:46 UTC, merged

2023-12-19 19:46 UTC, osuosl-manatee commented
Jenkins has merged this PR into `main` and has automatically performed a minor-level version bump to v1.1.0.  Have a nice day!